Fix required version of werkzeug>=2
I've received a Dependabot update for Quart 0.16, and it broke my build with the following error:

```
ModuleNotFoundError: No module named 'werkzeug.sansio'